apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: aap
  name: aap
spec:
  finalizers:
  - kubernetes
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: aap-j8hkh
  namespace: aap
spec:
  targetNamespaces:
  - aap
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ansible-automation-platform-operator.aap: ""
  name: ansible-automation-platform-operator
  namespace: aap
spec:
  channel: stable-2.7
  installPlanApproval: Automatic
  name: ansible-automation-platform-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
