apiVersion: v1
kind: Namespace
metadata:
  name: portworx
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/portworx-multi-cluster-certified.portworx: ""
  name: portworx-multi-cluster-certified
  namespace: portworx
spec:
  channel: stable
  installPlanApproval: Automatic
  name: portworx-multi-cluster-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: portworx-fn4zj
  namespace: portworx
spec:
  targetNamespaces:
  - portworx
  upgradeStrategy: Default